name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  release:
    types: [published]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11]
        os: [windows-latest, ubuntu-latest]
        exclude:
          - os: windows-latest
            java: adopt@1.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - run: git fetch --tags -f
      - run:
          # for GitOps tests
          git config --global user.email "scalafmt@scalameta.org" && git config --global user.name "scalafmt"
      - run: TEST="2.12" sbt ci-test-jvm
        shell: bash
      - run: TEST="2.13" sbt ci-test-jvm
        shell: bash
  test-scala-native:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8
      - if: matrix.os == 'windows-latest'
        name: setup windows environment
        run: ./bin/scala-native-setup/windows-setup.sh
      - if: matrix.os == 'macOS-latest'
        name: setup macOS environment
        run: ./bin/scala-native-setup/macos-setup.sh
      - if: matrix.os == 'ubuntu-latest'
        name: setup ubuntu environment
        run: ./bin/scala-native-setup/ubuntu-setup.sh
      - name: run tests
        run: |
          git fetch --tags -f
          # for GitOps tests	
          git config --global user.email "scalafmt@scalameta.org" && git config --global user.name "scalafmt"
      - run: TEST="2.12" sbt ci-test-native
        shell: bash
      - run: TEST="2.13" sbt ci-test-native
        shell: bash
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - run: ./scalafmt --test
      - run: yarn install
      - run: yarn format-check
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        libc: [default, musl]
        exclude:
          - os: macOS-latest
            libc: musl
        include:
          - os: macOS-latest
            artifact: scalafmt-macos
            env:
              NATIVE_IMAGE_STATIC: false
          - os: ubuntu-latest
            libc: default
            artifact: scalafmt-linux-glibc
            env:
              NATIVE_IMAGE_STATIC: true
          - os: ubuntu-latest
            libc: musl
            artifact: scalafmt-linux-musl
            env:
              NATIVE_IMAGE_STATIC: true
              NATIVE_IMAGE_MUSL: /home/runner/work/scalafmt/scalafmt/bundle
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm-ce-java11@20.1.0
      - if: matrix.libc == 'musl'
        name: Install musl bundle
        run: |
          wget https://github.com/gradinac/musl-bundle-example/releases/download/v1.0/musl.tar.gz
          tar xvf musl.tar.gz
      - run: bin/build-native-image.sh
        env:
          CI: true
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: scalafmt
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: scalafmt
          asset_name: ${{ matrix.artifact }}
          asset_content_type: application/zip
  dockerize:
    needs: [native-image,test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: scalameta/scalafmt
          tags: type=semver,pattern={{raw}}
      - name: Downloading scalafmt-linux-musl for Docker Build
        uses: actions/download-artifact@v2.0.10
        with:
          name: scalafmt-linux-musl
          path: tmp/scalafmt-linux-musl
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
